BOOKS = ("equity", "crypto")

EQUITY_TICKERS = ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "AMD"]
CRYPTO_TICKERS = ["BTC-USD", "ETH-USD", "ADA-USD", "XRP-USD"]

BARS_PER_YEAR = {"equity": 252, "crypto": 365}

DATE_START = "2019-01-01"
DATE_END = "2024-12-31"

FRED_SERIES = "T10Y2Y"
FRED_API_KEY_ENV = "FRED_API_KEY"

TRAIN_BARS = 365
TEST_BARS = 90
STEP_BARS = 90

TIER1_TRAIN_BARS = 200
TIER1_TEST_BARS = 40
TIER1_STEP_BARS = 40

VOL_WINDOW = 20
REBALANCE_EVERY = 5

CMA_POPULATION = 16
CMA_RESTARTS = 24
CMA_EVALS_PER_RESTART = 500
GROWTH_FLOOR = 1e-12

MAX_REFINEMENT_ATTEMPTS = 3
RECENT_RESULTS_WINDOW = 10

DEFAULT_ROUNDS = {"tier2": 5, "tier3": 50}

MIN_VARIABLES = 4
MAX_VARIABLES = 15

CONTRACT_SIMULATE_PARAMS = ("close", "high", "low", "volume", "macro", "x")
